language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: whsgqJjoNflo7sgHVIJJbRg8aYnr+7Bb/CZC5z9aKdDPXL1ZztgLtVlbV5ejjsGjUe/dQAjknLV+LuYvCk1iJslnksdgiyfq4KydxPkkk2YNLMdQ9fneEw6qMmoqjJg5s4huWJJbN+T+NAFDUB9e+0KoH4BNyBGHJGnJh8pAGjEu8pTgtkWGl0/KGQM/xzpRnz/5rS1EOw0D22vFjk3LEvtCMh96a8xOojNCMdZVck3TPbDpKTqgetLBIkydlj3ahAy8tvgIdFkiGWKnDQhs5bocKqnZ6p9sMUVLAaTS/qDdMqiruITh6rKuIU4VkEYMWbZUL8FHbBq3f/bi0OhwvxgNFKlf88tEQtiwelaXlpeoJ/IPoFDVLzh1RbIXmqPu76CjBvrGL8RpSJ2kqpAynJaUPLxcUAKsKs2HRJYJws6e6R9tBWIQGaTwbpQrCmNngNVAOIJpljRt5vBFUZgHk3x6sX9UudOwMDTLR1FBeXqxBetoOHZzzfOEXusTzZ1LF9UZ5wbYFjy9coZCxd7VSnhidO51dg55VuBq9SXkVgwbzu5JFw9/ZRyvO5OGFjKZz3TOcirmHOu3GK7PoHhaVgp/C7qomuGnHj6YsYolbWDB/4/rFkIxYcULCl2TyLiXMHnZchbZLwLDxZl/WdtpkBIeANv1APRjU/oMck/bKIQ=
before_install:
- openssl aes-256-cbc -K $encrypted_41338b3e2ea3_key -iv $encrypted_41338b3e2ea3_iv
  -in ./config/ssl/localhost.key.enc -out ./config/ssl/localhost.key -d
