language: node_js
node_js:
- 9
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_41338b3e2ea3_key -iv $encrypted_41338b3e2ea3_iv
  -in ./config/ssl/localhost.key.enc -out ./config/ssl/localhost.key -d
notifications:
  slack:
    secure: 2CRC0s7T4pcka8cl/3JTmkcDPlC5Yy+aiNRbWlDX6Hx+826xHy4cmMkJd0wJ7w0HQbBxdk2hCD+ZAGNOgyinq26l8j8so1IkYYqMwEpvWiNZLnaaAGPm/lz3SCUHbhdLGSa0Ahmn51Yt3d77mu4wvGLYDBySCbmu4pwgYbTPgV2vOlmsSjh77aWZZ/FunOLind+uGaad8yhmjDz2/mz11/xyqsm55loiJcNHG6aSaoY1I87b2C2ilJ5Qulm+1k2xk7t24hzMyt9+2KOfoVLiq+rUZXFDq546ErH1MKeoXQ2bn1Ou+C/QXt14mlUtyifJRQrk9b4g/1OHXvf1ENGUlcqC9AsBK7Q6M04zX0nlQ5wdXOmwFJVR2N2GuDv5Qcv8mJBCJSPHKtje7/DBrHMMJURwsy/BN4GL/AlWYMzsU09RcWh0yK6Kva2wR4SuUc9t++T/1X+aptUowwEG3gliDla8dzvSL/ovAi43SaTLzaZCFDPDU2Nw24riVkapNmETXacby8y2pfHsK7otjOwvoX7y2d3cUn+5cQGoA6B1q95USsB6GvvgaHLOU+CrppPlCi97VH+NoMOuGSUQ6UWSaboMFtjcuS55pphd7/c7aKQFHlj6Bspxsri+wMFbFOixd1sURn9FU3oJypDkOGAHNFj90tS8N/0aDBODUT0gn7Y=
env:
  global:
    secure: ZuTcSBIesj8Ym92re9IK22mDv08Ju3z6JWy88qPNvPemkGA33mBgaQWZ98Tx8Yq3B5e1DhEHyY6y9i4UyCzC5onjYsIOF0GJUSpPgEW+jtvxKlKY6orZ2zxiK+eVJfY72xCyoryylbzmxN4+/T/PfbI9c4BMjh6eQMIq/DxdO681hKhzxjHlS1ERn6NuGrmHyfRtOEDiVHJW3nVQjL63JTWiF1EKtIh8HDdcYJ5dYCs16vNthGabHpH/2UJr2S60H28xEBTZp6e3RNTmIiLMfisF2UjMVnXLlmNWNvVBFn1xJQojndCpygOOf/BoKz9ggBds3yoDy0WSVRVCG3XIpQxMyShdaL7ttJhc4DxwKMeavSAzdRGf19cyd8Bl52if6+rIa/NbpCVWqg2AGss2lHB3nG0o4a+W/nIaxcfV5TOIrza2yfVf8m34j6noOzOrpbzx2li0CslrmjCiaBXMTmDlITx4+bVReSYkzXCZZnKfS4ldn9N1yhKDy/1VngVXeKyy67axWlwB3UDujWgkY4N9W3J1iX0Jx31Et4AzkxSmf4onsAFiPMwRn0nRvgYz3M+DglXeLvstQgR8FwZoPmwvnajdmNeaKlKMNEw+/g1I8UMGEKtXw1dm5y5YFuVjY+c7txyzKY2QYpaDS5KbkY2lBn+PsAH4pix8PkDtTyA=
