language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_41338b3e2ea3_key -iv $encrypted_41338b3e2ea3_iv
  -in ./config/ssl/localhost.key.enc -out ./config/ssl/localhost.key -d
env:
  global:
    secure: WPlI5DM+Fdq+jc992Ntm8O8DT8rQS2tSqAto44qQWsh3hR+Kgpsf8io71Z2kBwLlC7HcWUhcAvTjj1MMDW4SMjaZZx6oXYTRr5e94w5KgZ8gP4zYoCXSomfSQR45k4ZmlwGNx5N42TSF0Wvw7vsX4w4T9BVPlx+Bctu9/AqNRdqu+OLbNr3RUNRmsH0AcdrSCZt5GlsFtdllXf8S8ufk6bSA2IVTrPjBOvqYzHn8mWenVww6akob/Zs2nM4iKO3ckdmySyuqa3j6X+wYtfh2HYd8FxmTJGBRkfkasLhUDwEEiulzc0M8W+vKt5rLD0znbkI6nYQeqBEr5SNBtHgMh7J3ED48sIk7Xpus55WVOXDpXPMwTTTg+NOByeFO9wN8jR9kxxuggr6sw9v6pDlmpnLPuSwbHk0t4JpE3gxwWw56x7LdLcc73ZzIhBJK+2XfhF2JbxhpMwSZVtndr7VacWZh6gpwAQQR8l9cOQ+UnlP8T1idlL1AvAYG0YkH735X+vyOkAJ+JsdJ24rsRq6IV6w0O0GrEcLWZO6ET8nhSv4gSigb1KIOC5KYwDe7YwZAuTamwZ9LKxhmJDVlpHYyRZMk6olxhuqYMgqZf0vW1wxb7VJNgQm7z2tGi3juGVpoLrK+32kJJs7AFP8VktYu4uY2xucWKMcfcl0XM+xRpJA=
notifications:
  slack:
    secure: YNw1bbkvyJF77eaLHthBkRCy0tIL6dHEzLvdacg1+sNCk/I93cd859W624BVVRF3io/Locuhmw7PDR9FAW0aTVdXxlEd3fZA4WuAT0MLvgstiLECyoLT9IE3f0X/UZ3QeKPIqETT/ntcQ++3XFtOwWo82vFrLaVYaOexNSv3JWoBzu/kUNmd7g9QkkqPITVpc5SEMK3MBPU6GuXL7d8ZXaf4LIJhSdIZhmWDSF98crqEFFWFDUzMHjhGBtVKnK+od4W0e76J4ALw2+0comgZCkY3J2DE5H5tjTgFtUVWdzs9/3CCk+neGh+zv/6DjI6D9XN+GU3ZsuTUaDHcCmPA2D1Ei+3y+um1yLcARnhOl1eeqwoGVu8xa3isq/lT8u0LlDOxMapUc9hEdyequy/jPM3Cfan9YRY7Io0uEToAf4+jaGmpgY9by+w+CFRgfK+IDVA3fsoybGLmGVR79ps4C3GiYkdzJQwfTG9NZD6RDoDyCD9pw64Y/FoSdKbqNX0r/5xXuxUx2jz52NR8qsz2PhNw+dunKLzRHuUfIMGhJ0Un3z6CF+7judF3UBOIqMfQOhiU3LecNOaT5IJcu6mss8vMm1uwLwd5dfLNByVo9M0XCvW6YtmPeV8ppj0KmHt1725mA+4niGAvDLUfzqgtQMypCxDI9Em4Ty4R5dFT2k4=
deploy:
- provider: npm
  api_key:
    secure: fOBnlZHLvGTB8rE/HMgYvYn4dfMFHlcIOKqlQ/mI6YAtCgpibDY9vvdZOlJj+c1TxSipLFSq+Zxa1RKdLep8RKDUO6u6wph6fRG1sJuByZEtdrf1J5ffvx8g39OltCYVdK80XXwP812J7gXuwNDS9vaAuf7RcIT5G7dzFCSbPrSBUjYewvwxxgkkH0aA/t6w+f5GlRLaLT65WtjS15oJeQeWOy5RGD6Zod74it+NnGxd1ZTG7JKu5GzT/V3B6TV7sQ5jJInsJHmdXG3TOpbdHNG5OIeySjY4rI0NS7GH0QBEzcCFGEvCNfQlrMq4oiR4dFeMzlgkrKaM5FvcjQdydSXfzPCeNpbHwLOVf/kk6RIQGs+9QoIjc5FsMNPC9RfqqJ2hNqGP5PNTiVc9KxIBE2eth1GCIezP1Om7M7yn7dS29r+E1FyGfmuNT6XZXcTYzXqsUxDtMzE5fTGbLK0xdVXutR9U6snuUS/ZdwY/1Wmy8BK+wLAj6telkhLe58f0v6x+bOrE24H8hRNSWhdKA8mDaZ/0o1tH0YwTbZcsRegSmcWia1aq+88Xzp+QNBaJWdBlz1qbQCbS/iF0ULFwEgaL+7iGzQ3nI+BmVM/cL7efz84cai8P84gO3jLoVe9Rb8rZAuorb3JTsP1NVQf8xW+UTVr+5mYUFJt2FQlk7EI=
  email:
    secure: q1Vd6+bcfvmemCX0rL3lE0ImyDAfuvVl2j5vFeqyEIQvmRZEjK1hj20fF/lTjzCULR2nuN7ykKlNQBk5Lw+ru317toN8j8jRhlbYoETBRivSzH2YyiRUBQ3bG5F6CjuydG2w1rbElgL5j2kUybG+tVztohsI5KQ1TvObC5h0bKPTXJf8GehnodMJIZSdyCf/XlgTmzD3FRGHMwuBiEH34a7TvjnZqmB1V+z5yhT2gTNOknatBmxiqWnrmqu3BT3OIyZAO/BRUz3GtN1FsdWXbqcBr3S45ApG6ggnmTtBSYNB2uVKLc7y3dyM4JpFFsks0i9Zt2MwszNoz+cwSlD8werXFg76/PMxbmraLE/c7L3MjZZYME4rX8rioEzfAf5qwtQoZQv7On3PPX1hT8px+5e0Ew4qWE3bGBaQnwlEaUMar7d2AlD7CgY93UWnXlufBL5wvwUqn9Dd0GZXCVUVxQSmoYcpCk31nTwX4zj1wNjgHa6P2jmHHGWuIbuKvgzZn8oRwGYJ0jB7w9geQQU6yhUnA1QpStcLhWXkh4hbWSFSlM4qcg6vH60xHjjPKZYj/fnN1WrMZUn3B9rPYYfG0L2LZF7Kb1LZfCRAvzCw0Q07/UoFKyOJd6FCwmBZOV+NPqAnpZW+JtB/qZ9Or9r3jROK4OSSYVS3qePatxOOKLA=
  on:
    branch: master
