language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_41338b3e2ea3_key -iv $encrypted_41338b3e2ea3_iv
  -in ./config/ssl/localhost.key.enc -out ./config/ssl/localhost.key -d
env:
  global:
    secure: ZuTcSBIesj8Ym92re9IK22mDv08Ju3z6JWy88qPNvPemkGA33mBgaQWZ98Tx8Yq3B5e1DhEHyY6y9i4UyCzC5onjYsIOF0GJUSpPgEW+jtvxKlKY6orZ2zxiK+eVJfY72xCyoryylbzmxN4+/T/PfbI9c4BMjh6eQMIq/DxdO681hKhzxjHlS1ERn6NuGrmHyfRtOEDiVHJW3nVQjL63JTWiF1EKtIh8HDdcYJ5dYCs16vNthGabHpH/2UJr2S60H28xEBTZp6e3RNTmIiLMfisF2UjMVnXLlmNWNvVBFn1xJQojndCpygOOf/BoKz9ggBds3yoDy0WSVRVCG3XIpQxMyShdaL7ttJhc4DxwKMeavSAzdRGf19cyd8Bl52if6+rIa/NbpCVWqg2AGss2lHB3nG0o4a+W/nIaxcfV5TOIrza2yfVf8m34j6noOzOrpbzx2li0CslrmjCiaBXMTmDlITx4+bVReSYkzXCZZnKfS4ldn9N1yhKDy/1VngVXeKyy67axWlwB3UDujWgkY4N9W3J1iX0Jx31Et4AzkxSmf4onsAFiPMwRn0nRvgYz3M+DglXeLvstQgR8FwZoPmwvnajdmNeaKlKMNEw+/g1I8UMGEKtXw1dm5y5YFuVjY+c7txyzKY2QYpaDS5KbkY2lBn+PsAH4pix8PkDtTyA=
notifications:
  slack:
    secure: eeh8cSieVHIL8qJ6U3sbj6jCI1Qi/EvWCASOGkRRcAP7e8PWzpjqFXVsSl0B4KcM9yciEdU6D+Gxa62upcnmck4pUjNp9GTFXttz6NqAB9je9mcVn168j/OBKseJ5suEx5itoxoltTMjq1gcsIIz19aDfZDKmNX2QUFh2jOp55T8pQ6n6qrTFkJNaiu8KhmxTAEvpdhOUIHQv1MLZSy1nKcmJtA7DyfftyalC097323tFAldx4QD4WFAPuP1Qxam7fPF/mpckYsSJqR+9bW9+d0bLSJ/MlZu7udam8YPa18fbCkvhPsEumzvlLkPKrkyXyYGMg5aOiwhOtp7GGY79dPQNam6qyMBokz/qCvZhGc4GNykjwFxGlx5TbTN4z5KwmtrEtN+t8aWGgAgjYBGyeNxcH0E+yGI9MsZk3+LmRBYpOrhqKAfmA8xLl0SPibyPHtdKfdoeT2+LEQs/DRrdwA3jLj0js+kl/abfuxEgiM5WQryHSlesqOHWJ0eQZl9BSNopSleBGCJYgEkkEV75ixxg/WtCcrpAs7JwvGcKAlmRRhcTSgJF8+fT3Q0oGD/04K40clFEpf8ZYyPveU2MJkqDJubwU5sHm/qzMf5GifqAH3d92Xm9ODPOEAS0X1zaYdukm7P0MldBxvsljdRB32bETXSfm1ophUP0snk9Wg=
