language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
  - secure: whsgqJjoNflo7sgHVIJJbRg8aYnr+7Bb/CZC5z9aKdDPXL1ZztgLtVlbV5ejjsGjUe/dQAjknLV+LuYvCk1iJslnksdgiyfq4KydxPkkk2YNLMdQ9fneEw6qMmoqjJg5s4huWJJbN+T+NAFDUB9e+0KoH4BNyBGHJGnJh8pAGjEu8pTgtkWGl0/KGQM/xzpRnz/5rS1EOw0D22vFjk3LEvtCMh96a8xOojNCMdZVck3TPbDpKTqgetLBIkydlj3ahAy8tvgIdFkiGWKnDQhs5bocKqnZ6p9sMUVLAaTS/qDdMqiruITh6rKuIU4VkEYMWbZUL8FHbBq3f/bi0OhwvxgNFKlf88tEQtiwelaXlpeoJ/IPoFDVLzh1RbIXmqPu76CjBvrGL8RpSJ2kqpAynJaUPLxcUAKsKs2HRJYJws6e6R9tBWIQGaTwbpQrCmNngNVAOIJpljRt5vBFUZgHk3x6sX9UudOwMDTLR1FBeXqxBetoOHZzzfOEXusTzZ1LF9UZ5wbYFjy9coZCxd7VSnhidO51dg55VuBq9SXkVgwbzu5JFw9/ZRyvO5OGFjKZz3TOcirmHOu3GK7PoHhaVgp/C7qomuGnHj6YsYolbWDB/4/rFkIxYcULCl2TyLiXMHnZchbZLwLDxZl/WdtpkBIeANv1APRjU/oMck/bKIQ=
  - secure: zfMd1Jqux4z1fVReN7nn9dIQyPTbmN2FT9RqBODrMfosMS+IU7Tmp6tjlzl/JSXvK+TNvGvvxok6+RA0uPOkV4Tm33shrgl9VvAzQjV4Qm71TSx0jHQKwEgDKRDLEFkZw8zmIsc/4X3Npooj5mhzWvnx70HDH8pb/yhsLxDbE8EssKHBs9lgflXtVXwzTm33DG7srcoX6fiYD7qabQXO12Ef30XnT/0tmqhji49UN7h6wBiFxfYXl9UsBcVjpJIiVA0Yjl/FNQZ1M75qj1LMRqQtEd3HCEtdaIPzohLhUBV8nlB9we3IsV/OiMtXt3SybsXMtWiWOkgufervtmjZuccgz+xG+RYjTOK2wT+v4ho7sky9p9DpmQOMaBAP+/Z+/fdMGt+BVveMS1RGphtn2NVLxIJfTkBSdR5arzLKolx0y/jOkncdLoW+DBOUytO+gHV4QO8ra8/mCq4XqdkoeMUVzQ54f42XgZzZSaClC6+BaRKROE1nrsol9j57EPQFamtaKOVRDhFzdUu8FEgEjlWXti+6+rQ+HEcslhZcgTLjxitILR8wAsj81oQ3d6uXevCnceng/z3oZpLwaywpHL7bUG0Jq6X+FknIWidAWUG2WZiQJ13nYKv3vk1zV5SXw37SuMBAERGP2WVMUFW/lDfFjNA8juxqKsAOZP9+5/c=
before_install:
- openssl aes-256-cbc -K $encrypted_41338b3e2ea3_key -iv $encrypted_41338b3e2ea3_iv
  -in ./config/ssl/localhost.key.enc -out ./config/ssl/localhost.key -d
notifications:
  slack:
    secure: 2CRC0s7T4pcka8cl/3JTmkcDPlC5Yy+aiNRbWlDX6Hx+826xHy4cmMkJd0wJ7w0HQbBxdk2hCD+ZAGNOgyinq26l8j8so1IkYYqMwEpvWiNZLnaaAGPm/lz3SCUHbhdLGSa0Ahmn51Yt3d77mu4wvGLYDBySCbmu4pwgYbTPgV2vOlmsSjh77aWZZ/FunOLind+uGaad8yhmjDz2/mz11/xyqsm55loiJcNHG6aSaoY1I87b2C2ilJ5Qulm+1k2xk7t24hzMyt9+2KOfoVLiq+rUZXFDq546ErH1MKeoXQ2bn1Ou+C/QXt14mlUtyifJRQrk9b4g/1OHXvf1ENGUlcqC9AsBK7Q6M04zX0nlQ5wdXOmwFJVR2N2GuDv5Qcv8mJBCJSPHKtje7/DBrHMMJURwsy/BN4GL/AlWYMzsU09RcWh0yK6Kva2wR4SuUc9t++T/1X+aptUowwEG3gliDla8dzvSL/ovAi43SaTLzaZCFDPDU2Nw24riVkapNmETXacby8y2pfHsK7otjOwvoX7y2d3cUn+5cQGoA6B1q95USsB6GvvgaHLOU+CrppPlCi97VH+NoMOuGSUQ6UWSaboMFtjcuS55pphd7/c7aKQFHlj6Bspxsri+wMFbFOixd1sURn9FU3oJypDkOGAHNFj90tS8N/0aDBODUT0gn7Y=
