language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_41338b3e2ea3_key -iv $encrypted_41338b3e2ea3_iv
  -in ./config/ssl/localhost.key.enc -out ./config/ssl/localhost.key -d
env:
  global:
    secure: hNq615Q24oFANFCzKNXoLKZn2AnZo0b2rsFRZUSUkudjYC1OGb9kitVOFJDNep93RarL2Pp+jM/CV0gzuZJADy+FZKl1BXE6UJ99aRNxsxOYkJMiRSk6ZUJ1EXYhH47X+8V4gcxYq4TKyW87NOhDz14RfVVyaG3b5zQYNV79mJeQYIu85/o1gHaLgeiaGBR13mq7QjwhCc3HOii/XHTZh8zKwzdadW+ABSt3NJa/3wUpvmlFDyzkW1OaUG/KcDZYcpjEGh2cL23YdQqmiT8ITlsp3Z5GvEtFFWLi3gD1VWtOeYO+WBM5B25sQakFuwMMJ687nVL2xxTBGdcwwDUI3K71DM1lp0AFOLbkBS7EE0JsYUsk8c6RkedQ6NgLx+hVH0fsbuIKG5N5ZyAhLIjJ5tKpLeQARbi5pNkn5XRzNRgz/2U866ZepY7UF4A43OS5zjrlQl4Sjvbnrly3CubaTh8nkG1ATZgRg1Qm3YXzLpEyRifwySHu1i5ahyV/7JQ3eUqVcdJqVmaTMkNV9QCR5J6nWYH5Xr4ug9k1Wlg2gkTcFu7avsUH4caiPx8Oul9pXSTCmlhwYsD2RO5hc15czXMtTCL+YKwX/EPE83wbaGoQkfHYtlaeTBMOuNGKLidwMUBiMESIC9k9aAUW6xo/1KxVUs33L2dxY5rq2rXg4RA=
notifications:
  slack:
    secure: c5WfDOQ/TuXlFl8UW8oD0/BZvBugb7XeUDNh9XDTGiAjvp/2gFswBbW6PuJ1xa4dtTPDbDiLMVMhwWfneko7b+phmfbvhY4O+eIS5vjTmG4OutrxdnB1HOaYPScuNtJih6IOYYaxc1yWHqqsQ/rjEzbkc49BdVc2FlIH+V0hfwt1ShdmKHP2x25zWZWqAw6vitV77PEIQFr32N8UApqlKKAmxp1C+7XJ3igNbHvwwhShbNwVbTPaHhrXlQx6FRjohUJY8brmFtJvrK8isBTJ2yAa6j4i9hrYQyV0Q+suf3gB7BdEsqfVNdJztaHxcqSnSPH0sqv5DRTrc8j7qivNGkiAc3zp7Jj2GHBq/xD9p2gjTSIMJrB7uivf0x3bAwgOEAYojFOMryoGCwbgUgEVjFfUZ0RnK2O+ev+gaDTO2SbfY9tQ0G1AWcuI9/2a0ascmhqO6Qtg7j8JySKtmWTbTghxNxDNsrG1I44wao6ulYmrPZgikEK80fcLYR/Jj2jhb6zPGg2ZOnnHELttnzLnrIenP/jwx60ou1lGObQygn0vL59wzy2Hfi/cfKspN8tdCiR83BnJD68Br1X5DfU2fwcd29fhB82H4xYcCJEj2B8gI2M7GMmT3RvG7iPuuYs3jr5otw0FDgV/vq9I2ktvKOxHw1MiM3IZuwJaI+Wu4hI=
deploy:
- provider: npm
  on:
    branch: master
  api_key:
    secure: qhOAHh0UJ/kka04w0jj3F0wqTzltu6wcDAf5UAA/5Zj0h/vOFt8GpjWKCOKqp843T2avniRhmAaEBXekHIESw3cnnJyV5wl9b0Z4axy5r1r3z93vxSnboLntMz7H39K2B9UtnE/YUTADCSpoqYgR6eQvXl1AwOHb2qMMK49nJDkaeU2HuqTPhbrAsodQzwAomId1WVTtHmGBU9LK0utcp0e09593FP5nqHCe0bsB4GVYsbu5/kAOmcEa3Q1EHnffk09BoFx+F8e2fuQLg1K+VodtTY4+AVq9oHKr/bK3DRHqRaBKt9n8kgEdw/QVNa3ZQtZApg+oV/i4PSNjzMBZQTmot7/CLQlqp//rhE0EB7DuZOX+WtlbyYco0QalRh7JNIZlMBR0BMaxD+jDIYPQivQD2zVLvSUH1OFBpvzBo/vo8VBPQayaB6WnEQUg6SCV60xvkZ8+AvW2oznDY5eVTBj5/10xx5Gvuhj6HNgvpKBTU8C3aJagzk/OEa7vGKwmPVpPtCygHqTd79PTvhM7e60Cv8Fyef3+Cbujwy7KI5ZUadAHeGSynhtb/Usj2B+Bd58YKx3+CQmcDOJ253MRLUMtrRrlRIdcwWtjBpxBrhKHE0hK96R+pyd1vtRILx66Smn4PnyFCZgC7ZDjAOR5ghX17n226RmZj6/Vr/0OowA=
  email:
    secure: qSGiCFrr9HzkWd6bnEIFu5aFLty0vdOvrtrCt8dwSnBPTyOnjFEjYwy9iauz7ksujpW1cRMqcJw8GgzbAaVp9sV4K7VInlpr7qyRfBwUU0YFcXHM+oM8DXCs0OH9H4A7aJ7JGoASzA3preics78ZTHByrsg65tZYRQjKfXil51ocfGYoDNRRdu/DGDLBphOLoeCZadS38swHIRbwLPO7IHm+hLbww5IKP9vCsdlsFPycfMBM13Sph6yKDaQxd/g54OW+Yzc4ChjDSWrE9eJMhQLOMSfiRHHnlHgoReIUledgcw5HgMYaUmF9sYavLfyhGseAStha5qXeQglihAAFOaSjgD6z79+eR1movqd0md980LNdeQw0l7SQPAMUpoYSMqJF1Ow0Nl4cfr6qN0Roj5qo/2+Qyummp+qxkgLdshFz7R7p/q0cKevQaF2MT2qCiVSnvqc8A1F2wmsglDrNX/zFJEcqJS7TmnVknHS04vS7e4LggRrxCJV8o+w9c/9+KNQIcNSYxZdoSRD3t9YpGG/q4SX4cJP84acx97g+FaFPnU7NAs+7vKCnr47XUmuDZumUcQdETRS63wCxzmpq3hrW260q5VI09JJxmMt3UVJLQec+MmO9r//Ho/FdLF1DARs/g2glCZuO4+t0QTS2xp+PsGfdBNLNxnCVB00cyu8=
